### ISSUE TITLE
AWSCore/AWSCore.h file not found

### ISSUE THREAD

**Issue by colinramsay** [morcmarc/react-native-cognito#1]
After following the README instructions, I find myself with the following error message:

`'AWSCore/AWSCore.h' file not found`

I've installed the AWS iOS SDK as per its instructions (I've tried both via pods and the framework methods) and no joy. I'm sure this is something straightforward but I'm just not sure what...

**Comment by colinramsay** [comment]
Well, dunno what was going on. I recreated the entire project and followed the same process and it works now. Sorry to bother you :wink:

**Comment by morcmarc** [comment]
Did you try adding the AWS iOS SDK path to your Header Search Path under Build Settings?

**Comment by colinramsay** [comment]
I just tried setting it to the location to which I downloaded the SDK and used the "recursive" option. Still no joy.

**Comment by morcmarc** [comment]
Could you try adding AWSCore.framework and AWSCognito.framework to your project, please? You can find them in your AWS SDK folder.

Edit: sorry, just noticed you've already tried that. 

Adding your AWS SDK path to Framework Search Path in RCTCognito.xcodeproj seems to solve the problem. Let me know if that doesn't work.

**Comment by colinramsay** [comment]
Adding to Framework Search Path indeed solve this problem, but it then gave me another issue which I'm not sure is related to your project. I'll look into it and re-open this if need be, thanks for your help.
