### ISSUE TITLE
Podspec file?

### ISSUE THREAD

**Issue by Vani-gurnani** [morcmarc/react-native-cognito#4]
Is there any way to use this for project's configured using Cocoa Pods?

Can you add podspec file as well for this?

**Comment by morcmarc** [comment]
Hi! Yeah, someone has already submitted a pullrequest for it #5 . I'll merge it in as soon as possible.

**Comment by morcmarc** [comment]
Looking into this I found that using CocoaPods for distributing RN packages is not idiomatic and the preferred method is NPM. Furthermore, React has been deprecated on CocoaPods
