### ISSUE TITLE
This project....

### ISSUE THREAD

**Issue by simonjblack** [morcmarc/react-native-cognito#6]
...is it dead? RN has now moved on to v0.29 and this is on v0.14.2!

**Comment by zevmo** [comment]
I would like to know as well.

**Comment by morcmarc** [comment]
Hi, "maintainer" here. I've been quite busy recently but more than happy to find some time and update the repo if there's people using it. Also happy to accept pull requests :-)

**Comment by jatazoulja** [comment]
I'll be needing this on some of my hacks, will fork and check what I can do for some missing features.

**Comment by satvikmaker** [comment]
@jatazoulja have you made any progress w.r.t. the Roadmap? Just curious... I see your fork is in-par with the main repo. Wanted to know if you have any changes that you have not pushed yet. :)

I would be needing this for a pretty big project, so wanted to know. I would add more code on top of the most updated code with time. Let me know.

@morcmarc How about your plans? :)

**Comment by jatazoulja** [comment]
@bozzmob no, I abandoned the project and implemented my own if you want here's the module:
https://codeshare.io/5P7dd2
I added 
- Login
- Create
- isLogin
- logout

Please note that I am doing this only for android. I don't have iOS knowledge to implement this... 
Let me know if you need anything else...

Cheers

**Comment by mtomic** [comment]
👍  for this project

**Comment by mtomic** [comment]
This may be useful - https://github.com/awslabs/aws-sdk-react-native/

**Comment by jmparsons** [comment]
Just published this: https://github.com/AirLabsTeam/react-native-aws-cognito-js/

**Comment by morcmarc** [comment]
Hi, apologies for the long radio silence. I am going to deprecate the package and promote using https://github.com/AirLabsTeam/react-native-aws-cognito-js/ instead. Thank you all for your interest!
